version: '3.8'

services:
  db:
    image: postgres:13.8
    container_name: jira_postgres

    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: jira_db

    ports:
      - "5432:5432" # external:internal

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: