version: '3.8'

services:
  db:
    image: postgres:13.8
    container_name: jira_postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_PORT}:5432" # external:internal

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  jira-connector:
    build:
      context: ./jira-connector
      dockerfile: Dockerfile
    container_name: jira_connector_service
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8003:8003"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_service
    depends_on:
      - db
      - jira-connector
    ports:
      - "8000:8000"

volumes:
  postgres_data: